### ISSUE TITLE
Get Request doesn't seem to work properly anymore

### ISSUE THREAD

**Issue by cluehr** [bulkan/robotframework-requests#90]
I gave version 0.4.0 a try which broke my tests. In the first place it seemed I was using the `Get Request` keyword in the wrong way (I was passing an URI including GET parameters which returned an error). After fixing this and using the `params` dictionary I got stuck with `RetryException`s. I was not able to find a reason for this. Testing the URL with a browser worked like a charm so I assume there is a bug in version 0.4.0.

**Comment by vkosuri** [comment]
@cluehr could share example testcase?

It is working fine in my machine with 0.4.0 version.

``` Robot
*** Settings ***
Library  Collections
Library  String
Library  .RequestsKeywords.py
Library  OperatingSystem
Suite Teardown  Delete All Sessions

*** Test Cases ***
Get Requests
    [Tags]  get
    Create Session  google  http://www.google.com
    Create Session  github  https://api.github.com

    ${resp}=  Get  google  /
    Should Be Equal As Strings  ${resp.status_code}  200

    ${resp}=  Get  github  /users/bulkan
    Should Be Equal As Strings  ${resp.status_code}  200
    Dictionary Should Contain Value  ${resp.json()}  Bulkan Evcimen
```

**Comment by oleduc** [comment]
@cluehr Hi, you're passing query parameters along with your uri, it will not work. It is a known bug and it is fixed by PR #86

**Comment by cluehr** [comment]
The following test works in version 0.3.9:


```
*** Settings ***
Documentation                           Deep Linking keywords
Library                                 RequestsLibrary
Library                                 Collections
Library                                 OperatingSystem


Suite Setup                             Prepare Session
Suite Teardown                          Delete All Sessions

*** Variables ***
${DEEP_LINKING_API_BASE_PATH}                 /api/deep-link

*** Keywords ***
Prepare Session
    ${proxies}=  Create Dictionary  http=http://10.44.217.99:8080  https=http://10.44.217.99:8080
    Create Session  deep-linking  http://suchen.mobile.de  proxies=${proxies}

*** Test Cases ***
Deep Linking 404 Test
    [Tags]  deepLinking
    ${response}=  Get Request  deep-linking  ${DEEP_LINKING_API_BASE_PATH}?link=http://suchen.mobile.de/lkw/gebraucht-gabelstapler.html
    Should Be Equal As Strings  ${response.status_code}  404
```

In version 0.4.0 I get the following error:

```
TypeError: get_request() got an unexpected keyword argument '/api/deep-link?link'
```

So I changed the test and put the URL parameters into a dictionary and provide the dictionary to `Get Request`:

```
Deep Linking 404 Test
    [Tags]  deepLinking
    ${params}=  Create Dictionary  link=http://suchen.mobile.de/lkw/gebraucht-gabelstapler.html
    ${response}=  Get Request  deep-linking  ${DEEP_LINKING_API_BASE_PATH}  headers=None  params=${params}
    Should Be Equal As Strings  ${response.status_code}  404
```

But now I get the RetryExceptions:

[ WARN ] host=suchen.mobile.de uri: /api/deep-link not responding, Retrying in 1.09 seconds ...
[ WARN ] host=suchen.mobile.de uri: /api/deep-link not responding, Retrying in 2.16 seconds ...
[ WARN ] host=suchen.mobile.de uri: /api/deep-link not responding, Retrying in 3.95 seconds ...
[ ERROR ] host=suchen.mobile.de uri: /api/deep-link not responding, Max. Retries reached quitting !!!
Deep Linking 404 Test                                               | FAIL |
RetryException: host=suchen.mobile.de uri: /api/deep-link not responding

**Comment by oleduc** [comment]
@cluehr Currently all exceptions are caught and converted into a RetryExceptions. I'd stay away from 0.4.0 until all outstanding pull requests are merged.

**Comment by jerry57** [comment]
This is a problem for us as well.  All of our "data=" lines are already formatted JSON.  I was able to keep our current "data=<formattedJSON>" by changing the following in RequestsKeywords.py

        #data = self._format_data_according_to_header(data, headers)
        data = self._utf8_urlencode(data)
This solved the problems with uri as well.  For the time being, we are using the v0.4.0 with above modification.

**Comment by vkosuri** [comment]
@jerry57 Could try replace **_format_data_according_to_header** procedure with below fix and let me know?

``` Python
def _format_data_according_to_header(self, data, headers):
    if data is not None and headers is not None and 'Content-Type' in headers:
        if headers['Content-Type'].find("application/json") != -1:
            # Check if data is already in json format or not
            if not _is_json(data):
                data = json.dumps(data)
        elif headers['Content-Type'].find("application/x-www-form-urlencoded") != -1:
            data = self._utf8_urlencode(data)
        else:
            data = data
    else:
        data = data

    return data
    
def _is_json(data):
  try:
    json = json.loads(data)
  except ValueError, e:
    return False
  return True
```

**Comment by bulkan** [comment]
@vkosuri I don't think you need the two `else`

**Comment by vkosuri** [comment]
@bulkan correct, in shorter version

``` Python
def _format_data_according_to_header(self, data, headers):
    if data is not None and headers is not None and 'Content-Type' in headers:
        if headers['Content-Type'].find("application/json") != -1 and not _is_json(data):
            data = json.dumps(data)
        elif headers['Content-Type'].find("application/x-www-form-urlencoded") != -1:
            data = self._utf8_urlencode(data)
        else:
            data = data
    return data
    
def _is_json(data):
  try:
    json = json.loads(data)
  except ValueError, e:
    return False
  return True
```

**Comment by bulkan** [comment]
@vkosuri even that remaining

```
else: 
    data = data
```

is unnecessary

**Comment by vkosuri** [comment]
Thank you @bulkan, yes it's overlook, will submit PR

**Comment by jerry57** [comment]
Did a clean checkout of master
added following in place of original _format_data_according_to_header code

def _format_data_according_to_header(self, data, headers):
    if data is not None and headers is not None and 'Content-Type' in headers:
        if headers['Content-Type'].find("application/json") != -1 and not _is_json(data):
            data = json.dumps(data)
        elif headers['Content-Type'].find("application/x-www-form-urlencoded") != -1:
            data = self._utf8_urlencode(data)
        else:
            data = data
    return data

def _is_json(data):
  try:
    json = json.loads(data)
  except ValueError, e:
    return False
  return True


Without modifying our old testcase, I am now seeing the following returned in stdout.  Will try to dig into it more when I get into the office

AttributeError: 'RequestsLibrary' object has no attribute '_format_data_according_to_header'

**Comment by jerry57** [comment]
Here is exactly what was entered in the source file:
`    def _format_data_according_to_header(self, data, headers):
        if data is not None and headers is not None and 'Content-Type' in headers:
            if headers['Content-Type'].find("application/json") != -1 and not _is_json(data):
                data = json.dumps(data)
            elif headers['Content-Type'].find("application/x-www-form-urlencoded") != -1:
                data = self._utf8_urlencode(data)
            else:
                data = data
        return data

    def _is_json(data):
        try:
            json = json.loads(data)
        except ValueError, e:
            return False
        return True
`

I am now seeing "NameError: global name '_is_json' is not defined" when running our testsuites

**Comment by vkosuri** [comment]
@jerry57 can you try to download the file from here? https://github.com/vkosuri/robotframework-requests/blob/get-req/src/RequestsLibrary/RequestsKeywords.py

**Comment by jerry57** [comment]
Tried that and am getting the same error, even after removing the installed library and reinstalling from source

**Comment by vkosuri** [comment]
could you share your RequestsLibrary.py

**Comment by jerry57** [comment]
I believe I have it committed here:
https://github.com/jerry57/robotframework-requests/blob/master/src/RequestsLibrary/RequestsKeywords.py

**Comment by vkosuri** [comment]
could you try to replace this ```_is_json``` function as below

``` Python
 def _is_json(data):
    try:
        json_obj = json.loads(data)
    except ValueError:
        return False
    return True
```

**Comment by vkosuri** [comment]
@jerry57 could you try again with latest changes of https://github.com/bulkan/robotframework-requests/pull/95

**Comment by jerry57** [comment]
I finally got a chance to give this a try today and am getting an "indent" error on the "except Value" line.  I have triple checked the spacing and indent and it seems correct.  It's like it needs something after the except ValueError line

**Comment by oleduc** [comment]
except ValueError as e:

**Comment by jerry57** [comment]
`
    def _is_json(data):
        try:
            json_obj = json.loads(data)
        except ValueError as e:
`
Is what I have and getting the indented error

**Comment by vkosuri** [comment]
These are common errors will get when there are combination of tabs and white spaces are included in your python code

If you are using notepad++ please enable tab and white space option

<img src = "http://www.martinrinehart.com/frontend-engineering/engineers/tools/notepad-pp/support/tabs02.jpg" />

Or if you are using ```vi``` or ```vim``` please add below lines in ```~/.vimrc```

<pre>
" Enable space tab$
 set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<$
 set list$
</pre>

**Comment by girishsortur** [comment]
Any updates on this issue? I have `robotframework-requests (0.4.4)` but still get this error. Or can anyone let me know what version to install in order to avoid this error? Thanks

**Comment by vkosuri** [comment]
@girishsortur could you share screen shot of you error? and full stack trace?

**Comment by jerry57** [comment]
I tried the latest this morning again (0.4.4) and our testcases still failed.  I replaced the following line in 3 locations (POST, PATCH, PUT REQUESTS) and the problem appears to go away.

`    #data = self._format_data_according_to_header(data, headers)
    data = self._utf8_urlencode(data)
`
This was sighted in our original assessment of the issue.

**Comment by bulkan** [comment]
Can you share a sample testcase file with a failing test ?

**Comment by girishsortur** [comment]
@vkosuri I am facing issue with SSLError currently and so i am not able to reproduce this error. When i try to run scripts i get following error -

```
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
```
Here's the full trace i got -

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/RequestsLibrary/RequestsKeywords.py", line 166, in get_request
    response = self._get_request(session, uri, headers, params, redir)
  File "/Library/Python/2.7/site-packages/RequestsLibrary/RequestsKeywords.py", line 461, in _get_request
    allow_redirects=allow_redirects)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request) 
```

Is this an issue with `robotframework-requests` or `Requests`?

**Comment by bulkan** [comment]
@girishsortur I've never seen that exception before and a quick good found this result;

http://stackoverflow.com/questions/14102416/python-requests-requests-exceptions-sslerror-errno-8-ssl-c504-eof-occurred

**Comment by girishsortur** [comment]
Thanks @bulkan. I upgraded my openssl version and i am not getting this error anymore. Now i am getting a different error, not sure what this means - 

```
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
```

I tried searching online but didn't any help on that. Any ideas on this?
